# Schema for the configuration files of the Testingapp module.
testingapp.settings:
  type: config_object
  label: 'Testingapp settings'
  mapping:
    example:
      type: string
      label: 'Example'
